esphome:
  name: "${name}"
  friendly_name: Apollo PUMP-1
  comment: Apollo PUMP-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.PUMP-1"
    version: "${version}"

  min_version: 2023.11.1

dashboard_import:
  package_import_url: github://SteffenSenchyna/PUMP-1/Integrations/ESPHome/PUMP-1.yaml@main
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:
    ssid: "Apollo PUMP-1 Hotspot"

logger:

packages:
  core: !include Core.yaml
